name: Build and Deploy Image Container

on:
  push:
    branches: [ 'main' ]
    paths-ignore:
      - '**/README.md'

env:
  DOTNET_VERSION: '8.0.x' 
  BUILD_CONFIGURATION: 'Release'    
  SONAR_CLOUD_PROJECT_KEY: 'Xhaguatende_blazor-demo'
  PUBLISH_PROJECT: 'BlazorDemo.WebApp/BlazorDemo.WebApp.csproj'
  DOCKER_HUB_REPOSITORY: 'blazor-demo'

defaults:
  run:
    working-directory: ./src

# Ensures only one execution per branch will run at a time.
concurrency:
  group: ${{ github.ref }}
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17' # Set up Java 17, because SonarCloud requires it
        distribution: 'adopt' 

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.7
      with:
        versionSpec: '5.x'

    - name: Setup GitVersion
      uses: gittools/actions/gitversion/execute@v0.9.7
      id: gitversion

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
        source-url: ${{ secrets.PACKAGES_FEED_URL }}
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.NUGET_AUTH_TOKEN }}

    - name: Cache .NET Core packages
      uses: actions/cache@v2
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-dotnet-${{ hashFiles('**/*.csproj') }}
        restore-keys: |
          ${{ runner.os }}-dotnet-

    - name: Cache SonarCloud packages
      uses: actions/cache@v2
      with:
        path: ~\.sonar\cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar
            
    - name: Restore dependencies
      run: dotnet restore

    - name: Install SonarCloud
      run: dotnet tool install --global dotnet-sonarscanner

    - name: Begin SonarCloud Scan
      run: |
            dotnet sonarscanner begin /o:"${{ secrets.SONAR_CLOUD_ORGANIZATION }}" \
                                    /k:"${{ env.SONAR_CLOUD_PROJECT_KEY }}" \
                                    /v:"${{ steps.gitversion.outputs.nuGetVersionV2 }}" \
                                    /d:sonar.host.url="${{ secrets.SONAR_CLOUD_URL }}" \
                                    /d:sonar.token="${{ secrets.SONAR_TOKEN }}" \
                                    /d:sonar.cs.opencover.reportsPaths=./CoverageResults/coverage.opencover.xml \
                                    /d:sonar.coverage.exclusions="**Test*.cs" \
                                    /d:sonar.qualitygate.wait=true
   
    - name: Build
      run: dotnet build --no-restore --configuration ${{ env.BUILD_CONFIGURATION }} -p:GeneratePackageOnBuild=false


    - name: End SonarCloud Scan
      run: dotnet sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Publish WebApp
      run: dotnet publish ${{ env.PUBLISH_PROJECT }} --no-build --configuration ${{ env.BUILD_CONFIGURATION }} --output './../publish'
   
    - name: Login to Docker Hub Registry
      uses: docker/login-action@v3
      with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}      

    - name: Build and Push Image to Docker Hub Registry
      if: steps.gitversion.outputs.CommitsSinceVersionSource > 0
      uses: docker/build-push-action@v5
      with:
        context: .
        file: docker/Dockerfile.WebApp
        push: true
        tags: ${{secrets.DOCKERHUB_USERNAME}}/${{env.DOCKER_HUB_REPOSITORY}}:${{ steps.gitversion.outputs.nuGetVersionV2 }}
        labels: |
            org.opencontainers.image.title=BlazorDemo.WebApp
            org.opencontainers.image.description=BlazorDemo.WebApp
            org.opencontainers.image.version=${{ steps.gitversion.outputs.nuGetVersionV2 }}

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      if: steps.gitversion.outputs.CommitsSinceVersionSource > 0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ steps.gitversion.outputs.nuGetVersionV2}}
        release_name: Release ${{ steps.gitversion.outputs.nuGetVersionV2}}
